import type { NightConfig } from '../types/index';

export const NIGHT_CONFIGS: NightConfig[] = [
  // ============================================================
  // NIGHT 1 — Tutorial night
  // ============================================================
  {
    night: 1,
    noteType: 'none',
    noteDescription: '',
    roles: [
      {
        title: 'Fight Double',
        stuntType: 'fight',
        riskLevel: 'medium',
        requiredGender: 'male',
        heightRange: [66, 72],
        weightRange: [160, 200],
        requiredSkills: ['fight'],
        sagRequired: false,
      },
      {
        title: 'Crowd Reaction',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 4,
    bribeRange: [0, 0],
    sagRepChance: 0,
    ndUpgradeChance: 0,
    wigGuyAppears: false,
    returningVisitorChance: 0,
    kidExpenseChance: 0,
    openingMonologue: "A week of overnights. I would say I've done worse... if I could even remember...",
    closingMonologue: 'Not bad. 11 hours in the dark. But I survived.',
    hiringDeadline: 24,
  },

  // ============================================================
  // NIGHT 2 — Locals only
  // ============================================================
  {
    night: 2,
    noteType: 'locals_only',
    noteDescription: 'Production wants locals only tonight.',
    roles: [
      {
        title: 'High Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['high_fall'],
        sagRequired: false,
      },
      {
        title: 'Car Reaction',
        stuntType: 'car_hit',
        riskLevel: 'medium',
        requiredGender: 'any',
        heightRange: [62, 74],
        weightRange: [130, 220],
        requiredSkills: ['car_hit'],
        sagRequired: false,
      },
      {
        title: 'Street Walk-By',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 5,
    bribeRange: [15, 30],
    sagRepChance: 0,
    ndUpgradeChance: 0,
    wigGuyAppears: true,
    returningVisitorChance: 0,
    kidExpenseChance: 0.6,
    openingMonologue: "I feel like I'm jet lagged but I'm at home. This is going to be a long week.",
    closingMonologue: 'Someone tried to bribe me $20. I thought about it for way too long.',
    hiringDeadline: 24,
  },

  // ============================================================
  // NIGHT 3 — Added role
  // ============================================================
  {
    night: 3,
    noteType: 'added_role',
    noteDescription: 'Production added an extra role mid-shift.',
    roles: [
      {
        title: 'Stair Fall',
        stuntType: 'stair_fall',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [160, 210],
        requiredSkills: ['stair_fall'],
        sagRequired: false,
      },
      {
        title: 'Fight Double',
        stuntType: 'fight',
        riskLevel: 'medium',
        requiredGender: 'male',
        heightRange: [66, 72],
        weightRange: [160, 200],
        requiredSkills: ['fight'],
        sagRequired: false,
      },
      {
        title: 'Ratchet Pull',
        stuntType: 'ratchet',
        riskLevel: 'medium',
        requiredGender: 'any',
        heightRange: [64, 74],
        weightRange: [140, 210],
        requiredSkills: ['ratchet'],
        sagRequired: false,
      },
      {
        title: 'Explosion BG',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 5,
    bribeRange: [30, 60],
    sagRepChance: 0,
    ndUpgradeChance: 0,
    wigGuyAppears: false,
    returningVisitorChance: 0,
    kidExpenseChance: 0,
    openingMonologue: "How does everyone know what I'm hiring for? It's 1 AM.",
    closingMonologue: 'Three nights down. Four to go.',
    hiringDeadline: 23.5,
  },

  // ============================================================
  // NIGHT 4 — Stunt change
  // ============================================================
  {
    night: 4,
    noteType: 'stunt_change',
    noteDescription: 'Car hit is now a high fall.',
    roles: [
      {
        title: 'High Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['high_fall'],
        sagRequired: false,
      },
      {
        title: 'Balcony Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'any',
        heightRange: [64, 72],
        weightRange: [130, 200],
        requiredSkills: ['high_fall'],
        sagRequired: false,
      },
      {
        title: 'Wire Pull',
        stuntType: 'wire_work',
        riskLevel: 'medium',
        requiredGender: 'any',
        heightRange: [62, 74],
        weightRange: [130, 210],
        requiredSkills: ['wire_work'],
        sagRequired: false,
      },
      {
        title: 'Diner Patrons',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 6,
    bribeRange: [40, 80],
    sagRepChance: 0.3,
    ndUpgradeChance: 0,
    wigGuyAppears: true,
    returningVisitorChance: 0.7,
    kidExpenseChance: 0.8,
    openingMonologue: 'Halfway. My back is a federal crime.',
    closingMonologue: "My back is killing me. Physical therapy bill just went up again.",
    hiringDeadline: 23,
  },

  // ============================================================
  // NIGHT 5 — Budget cut (no ND)
  // ============================================================
  {
    night: 5,
    noteType: 'budget_cut',
    noteDescription: 'Budget cuts — no ND spots tonight.',
    roles: [
      {
        title: 'Fire Gag',
        stuntType: 'fire_gag',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['fire_gag'],
        sagRequired: false,
      },
      {
        title: 'High Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'any',
        heightRange: [66, 74],
        weightRange: [150, 210],
        requiredSkills: ['high_fall'],
        sagRequired: false,
      },
      {
        title: 'Fight Sequence',
        stuntType: 'fight',
        riskLevel: 'medium',
        requiredGender: 'male',
        heightRange: [66, 72],
        weightRange: [160, 200],
        requiredSkills: ['fight'],
        sagRequired: false,
      },
    ],
    visitorCount: 6,
    bribeRange: [50, 100],
    sagRepChance: 0.4,
    ndUpgradeChance: 0,
    wigGuyAppears: false,
    returningVisitorChance: 0.5,
    kidExpenseChance: 0.5,
    openingMonologue: 'No ND spots tonight. Nowhere to hide.',
    closingMonologue: 'My cousin does HVAC. Benefits. Sleeps at night.',
    hiringDeadline: 24,
  },

  // ============================================================
  // NIGHT 6 — Non-union
  // ============================================================
  {
    night: 6,
    noteType: 'non_union',
    noteDescription: 'Going non-union tonight.',
    roles: [
      {
        title: 'Explosion Ratchet',
        stuntType: 'ratchet',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['ratchet', 'explosion_reaction'],
        sagRequired: false,
      },
      {
        title: 'Car Hit',
        stuntType: 'car_hit',
        riskLevel: 'high',
        requiredGender: 'any',
        heightRange: [64, 74],
        weightRange: [140, 220],
        requiredSkills: ['car_hit'],
        sagRequired: false,
      },
      {
        title: 'High Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['high_fall'],
        sagRequired: false,
      },
      {
        title: 'Fight Combo',
        stuntType: 'fight',
        riskLevel: 'medium',
        requiredGender: 'any',
        heightRange: [64, 74],
        weightRange: [140, 210],
        requiredSkills: ['fight'],
        sagRequired: false,
      },
      {
        title: 'Background Scatter',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 7,
    bribeRange: [75, 150],
    sagRepChance: 0.6,
    ndUpgradeChance: 0.7,
    wigGuyAppears: true,
    returningVisitorChance: 0.6,
    kidExpenseChance: 0.8,
    openingMonologue: "Going non-union tonight. This'll be interesting.",
    closingMonologue: 'One more night. One. More. Night.',
    hiringDeadline: 23,
  },

  // ============================================================
  // NIGHT 7 — Final night
  // ============================================================
  {
    night: 7,
    noteType: 'added_role',
    noteDescription: 'Last-minute role added. Fill everything.',
    roles: [
      {
        title: 'Explosion Ratchet',
        stuntType: 'ratchet',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 210],
        requiredSkills: ['ratchet', 'explosion_reaction'],
        sagRequired: false,
      },
      {
        title: 'High Fall',
        stuntType: 'high_fall',
        riskLevel: 'high',
        requiredGender: 'any',
        heightRange: [66, 74],
        weightRange: [150, 210],
        requiredSkills: ['high_fall'],
        sagRequired: true,
      },
      {
        title: 'Car Hit',
        stuntType: 'car_hit',
        riskLevel: 'high',
        requiredGender: 'male',
        heightRange: [68, 74],
        weightRange: [170, 220],
        requiredSkills: ['car_hit'],
        sagRequired: true,
      },
      {
        title: 'Fight Double',
        stuntType: 'fight',
        riskLevel: 'medium',
        requiredGender: 'male',
        heightRange: [66, 72],
        weightRange: [160, 200],
        requiredSkills: ['fight'],
        sagRequired: false,
      },
      {
        title: 'Background Scatter',
        stuntType: 'explosion_reaction',
        riskLevel: 'nd',
        requiredGender: 'any',
        heightRange: [60, 76],
        weightRange: [110, 250],
        requiredSkills: [],
        sagRequired: false,
      },
    ],
    visitorCount: 8,
    bribeRange: [50, 200],
    sagRepChance: 0.5,
    ndUpgradeChance: 0.5,
    wigGuyAppears: true,
    returningVisitorChance: 0.8,
    kidExpenseChance: 0.6,
    openingMonologue: 'Last night. Whatever happens, this is the last night.',
    closingMonologue: "After tonight, I'm done. For at least a week. Maybe forever.",
    hiringDeadline: 22,
  },
];
